version: "3.7"

services:
  npm:
    container_name: npm
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - 4343:80 # http
      - 4344:81 # for web interface
      - 4345:443 # https
    volumes:
      - ${CONTAINER_DIR}/npm/data:/data
      - ${CONTAINER_DIR}/npm/letsencrypt:/etc/letsencrypt

  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    group_add:
      - "104"
    devices:
      #- /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    volumes:
      - ${CONTAINER_DIR}/media_server/jellyfin/config:/config
      - ${SENTINEL_DIR}/media_server/media/tvshows:/data/tvshows
      - ${SENTINEL_DIR}/media_server/media/movies:/data/movies
    ports:
      - 8096:8096
        #- 8920:8920 #optional
        #- 7359:7359/udp #optional
        #- 1900:1900/udp #optional
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - ${CONTAINER_DIR}/media_server/sonarr/config:/config
      - ${SENTINEL_DIR}/media_server/media/tvshows:/tv #optional
      - ${SENTINEL_DIR}/media_server/downloads/complete:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - ${CONTAINER_DIR}/media_server/radarr/config:/config
      - ${SENTINEL_DIR}/media_server/media/movies:/movies #optional
      - ${SENTINEL_DIR}/media_server/downloads/complete:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - ${CONTAINER_DIR}/media_server/sabnzbd/config:/config
      - ${SENTINEL_DIR}/media_server/downloads/complete:/downloads #optional
      - ${SENTINEL_DIR}/media_server/downloads/incomplete:/incomplete-downloads #optional
    ports:
      - 6767:8080
    dns:
      - "192.168.1.1"
    restart: unless-stopped

  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    ports:
      - 8888:8888
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    devices:
      - /dev/dri:/dev/dri       # For H/W transcoding using the VAAPI encoder
    volumes:
      - ${CONTAINER_DIR}/media_server/unmanic/config:/config
      - ${SENTINEL_DIR}/media_server/media/movies:/library/movies
      - ${SENTINEL_DIR}/media_server/media/tvshows:/library/tvshows
      - ${CONTAINER_DIR}/media_server/unmanic/cache:/tmp/unmanic
    restart: unless-stopped

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    environment:
         - LOG_LEVEL=debug
         - TZ=Asia/Singapore
    ports:
         - 5055:5055
    volumes:
         - ${CONTAINER_DIR}/media_server/jellyseerr/config:/app/config
    restart: unless-stopped

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ${CONTAINER_DIR}/smart_home/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ${CONTAINER_DIR}/smart_home/mosquitto/data:/mosquitto/data
      - ${CONTAINER_DIR}/smart_home/mosquitto/log:/mosquitto/log
    restart: unless-stopped

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    ports:
      - 8081:8080
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_f8b77f547945ed11ad45ca8f0a86e0b4-if00-port0:/dev/ttyUSB0
    volumes:
      - ${CONTAINER_DIR}/smart_home/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Asia/Singapore
    restart: unless-stopped
    depends_on:
      - mqtt
      - homeassistant

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: "host"
    volumes:
      - ${CONTAINER_DIR}/smart_home/homeassistant:/config
    environment:
      - TZ=Asia/Singapore
    privileged: true
    restart: unless-stopped


  nextcloud-db:
    container_name: nextcloud-db
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ${CONTAINER_DIR}/nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  nextcloud-app:
    container_name: nextcloud
    image: nextcloud
    ports:
      - 8080:80
    links:
      - nextcloud-db
    volumes:
      - ${SENTINEL_DIR}/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
    restart: unless-stopped

  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - 3000:3000
    volumes:
      - ${CONTAINER_DIR}/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
      - /sentinel:/disk
    restart: unless-stopped

  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - 1111:8080 # webapp
      - 1112:8086 # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ${CONTAINER_DIR}/scrutiny/config:/opt/scrutiny/config
      - ${CONTAINER_DIR}/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
      - /dev/sde

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "immich" ]
    volumes:
      - ${SENTINEL_DIR}/photos/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - immich-redis
      - immich-database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${SENTINEL_DIR}/photos/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - immich-redis
      - immich-database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${SENTINEL_DIR}/model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    env_file:
      - .env
    restart: always

  immich-database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${SENTINEL_DIR}/database:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
