version: "3.7"

services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    group_add:
      - "109"
    devices:
      #- /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    volumes:
      - /home/stephen/docker/containers/media_server/jellyfin/config:/config
      - /home/stephen/docker/containers/media_server/media/tvshows:/data/tvshows
      - /home/stephen/docker/containers/media_server/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - /home/stephen/docker/containers/media_server/sonarr/config:/config
      - /home/stephen/docker/containers/media_server/media/tvshows:/tv #optional
      - /home/stephen/docker/containers/media_server/downloads/complete:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - /home/stephen/docker/containers/media_server/radarr/config:/config
      - /home/stephen/docker/containers/media_server/media/movies:/movies #optional
      - /home/stephen/docker/containers/media_server/downloads/complete:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - /home/stephen/docker/containers/media_server/sabnzbd/config:/config
      - /home/stephen/docker/containers/media_server/downloads/complete:/downloads #optional
      - /home/stephen/docker/containers/media_server/downloads/incomplete:/incomplete-downloads #optional
    ports:
      - 8080:8080
    dns:
      - "192.168.1.1"
    restart: unless-stopped

  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    ports:
      - 8888:8888
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    devices:
      - /dev/dri:/dev/dri       # For H/W transcoding using the VAAPI encoder
    volumes:
      - /home/stephen/docker/containers/media_server/unmanic/config:/config
      - /home/stephen/docker/containers/media_server/media/movies:/library/movies
      - /home/stephen/docker/containers/media_server/media/tvshows:/library/tvshows
      - /home/stephen/docker/containers/media_server/unmanic/cache:/tmp/unmanic
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
         - LOG_LEVEL=debug
         - TZ=Asia/Singapore
    ports:
         - 5055:5055
    volumes:
         - /home/stephen/docker/containers/media_server/jellyseerr/config:/app/config
    restart: unless-stopped

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /home/stephen/docker/containers/smart_home/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /home/stephen/docker/containers/smart_home/mosquitto/data:/mosquitto/data
      - /home/stephen/docker/containers/smart_home/mosquitto/log:/mosquitto/log
    restart: unless-stopped

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    ports:
      - 8081:8080
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_f8b77f547945ed11ad45ca8f0a86e0b4-if00-port0:/dev/ttyUSB0
    volumes:
      - /home/stephen/docker/containers/smart_home/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Asia/Singapore
    restart: unless-stopped
    depends_on:
      - mqtt
      - homeassistant

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: "host"
    volumes:
      - /home/stephen/docker/containers/smart_home/homeassistant:/config
    environment:
      - TZ=Asia/Singapore
    privileged: true
    restart: unless-stopped
